server:
  port: 9004

swagger:
  server:
    url: ${_SWAGGER_SERVER_URL}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${_SERVICE_URL_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
  
  
  kafka:
    bootstrap-servers: ${_BOOTSTRAP_SERVER}
    consumer:
      bootstrap-servers: ${_BOOTSTRAP_SERVER}
      group-id: ${_KAFKA_GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      bootstrap-servers: ${_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${_DATASOURCE_URL}
    username: ${_DATASOURCE_USERNAME}
    password: ${_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    username: "smartride6@gmail.com"
    password: "hejrxqfjlthbstvq"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${_ISSUER_URI}
          jwk-set-uri: ${_JWK_SET_URI}

      client:
        registration:
          resource:
            authorization-grant-type: client_credentials
            client-id: user-microservice
            client-secret: ${_CLIENT_SECRET}
            redirect-uri: ${_REDIRECT_URI}
        provider:
          resource:
            token-uri: ${_TOKEN_URI}


  redis:
    host: "localhost"
    port: ${_REDIS_PORT}

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuit breaker:
    instances:
      keycloak:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 70
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        ignore-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.Unauthorized
      chat:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 70
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        ignore-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
