BOOTSTRAP_SERVER: http://127.0.0.1:9092
CLIENT_ID: user-service
CLIENT_SECRET: dYhLOy6m2f8lsZERJIEJNhO9smmdLNfp
DATASOURCE_PASSWORD: password
DATASOURCE_URL: jdbc:postgresql://localhost:5432/users
DATASOURCE_USERNAME: keycloak
GATEWAY_NAME: gateway
HOSTNAME: localhost
ISSUER_URI: http://localhost:8080/realms/ICMSS
JWK_SET_URI: http://localhost:8080/realms/ICMSS/protocol/openid-connect/certs
KEYCLOAK_URI: http://localhost:8080
MAIL_PASSWORD: spzb jcoh qyui vzhv
MAIL_USERNAME: msender038@gmail.com
REDIRECT_URI: http://localhost:9010/authorized
REDIS_HOST: localhost
REDIS_PORT: 6379
SERVICE_URL_DEFAULT_ZONE: http://localhost:9001/eureka
SWAGGER_SERVER_URL: http://localhost:9003/user-service
TOKEN_URI: http://localhost:8080/realms/ICMSS/protocol/openid-connect/token
